### ISSUE TITLE
Dist Folder Structure Broken

### ISSUE THREAD

**Issue by juliovalcarcel** [taigaio/taiga-front-dist#10]
Since 1.9.1 the dist folder does not have the proper hierarchy and instead has a v-xxxxxxxx folder containing all the relevant files.

**Comment by superalex** [comment]
it's the  desired new format, everytime the front is compiled that folder changes with a timestamp, this way we avoid a lot of browser cache problems related ;)

**Comment by juliovalcarcel** [comment]
Is this changed documented anywhere that I may have missed? I was following the installation guide https://taigaio.github.io/taiga-doc/dist/setup-production.html and it made no note of it.

**Comment by bameda** [comment]
In https://taigaio.github.io/taiga-doc/dist/upgrades.html#_upgrades_notes for upgrades

**Comment by juliovalcarcel** [comment]
Okay, thank you for the clarification!

**Comment by bameda** [comment]
You are welcome :-)
