### ISSUE TITLE
Is there any way to change app theme ?

### ISSUE THREAD

**Issue by mayuroks** [taigaio/taiga-front-dist#11]
The overall tools is really nice and easy to setup. I just wanna there any way to change app theme ?
I am certain a lot of "humans" in my team wont be able work with current UI. Please let me know

**Comment by Xaviju** [comment]
Taiga offers three themes (color schemes) by default on the admin panel. 
You can create your own themes: https://taigaio.github.io/taiga-doc/dist/#themes

Please share your theme with other users if you create a custom one.
