### ISSUE TITLE
Do you plan to make a new 3.1.1 release ?

### ISSUE THREAD

**Issue by max-k** [taigaio/taiga-front-dist#16]
Thank you very much.

**Comment by xgid** [comment]
If there are no plans for an update of the project in the near future, another option would be to share with us how could we generate an updated `taiga-front-dist` from the stable version of the `taiga-front` project.

Would it be possible?

Maybe it's in the docs somewhere, but I could not find it.

**Comment by m-terlinde** [comment]
Is it planned, that users migrate to "taiga-front"?
Your installation documentation mentiones this package for the frontend installation.

**Comment by alexhermida** [comment]
Hi @max-k we just to update it. 

@xgid don't worry we plan to keep this repo updated.

@m-terlinde you can use either of the two. This repo seems to be more convenient if you don't want to compile frontend dependences.

**Comment by m-terlinde** [comment]
Thanks alex for your answer!
Do you have a roadmap or a date for the new release?

Is it possible/safe to use the current stable backend version (3.1.3) with the current front-dist version?

**Comment by fedebaier** [comment]
Do you plan to automate the process somehow? Because the taiga-front is already in the 3.2.1 release.
Thanks.

**Comment by IwishIcanFLighT** [comment]
Bumping that issue with 3.3.0 released more than a week ago and 3.3.1 4 days ago. :confused: 

It would be indeed very interesting to automate the process so this repo can keep up with taiga's 2018 release pace.

Thanks

**Comment by fedebaier** [comment]
@IwishIcanFLighT I stopped using this repo, instead I just compile the taiga-front myself.

**Comment by alexhermida** [comment]
@IwishIcanFLighT @fedebaier you are right, sorry for the delay. We released 3.3.0 with some issues that we've been fixing in 3.3.1. We just updated this repo with 3.3.1.

As @IwishIcanFLighT said we'll evaluate to automate this repo.

**Comment by m-terlinde** [comment]
> I stopped using this repo, instead I just compile the taiga-front myself.

Yeah, but a git pull is much easier for busy admins ;).
