### ISSUE TITLE
Error: Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by sandip3dec** [taigaio/taiga-front-dist#18]
gulp serve
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-util'

**Comment by migonzalvar** [comment]
Sorry, I really don't understand. Maybe your are talking about https://github.com/taigaio/taiga-front ?

**Comment by sandip3dec** [comment]
thank you so much for the help can you just suggest that how can we connect
RESTAPI of adonisjs with angularjs.
