### ISSUE TITLE
Mixed Content Warning

### ISSUE THREAD

**Issue by pigmonkey** [taigaio/taiga-front-dist#2]
I'm not sure what repository is most appropriate for this issue. Sorry if this isn't it.

I followed the [setup production environment](https://taigaio.github.io/taiga-doc/dist/setup-production.html) docs. I setup nginx to serve everything over HTTPS right off the bat. When I visited my site, it became apparent that the front-end was not communicating with the API. When I opened up the development console I saw that there was a request being made to http://localhost:8000, which was being blocked by the browser with a mixed content warning. I was surprised to see this since I had set both the `SITES` setting in the back-end and the `api` variable in the front end `/dist/js/config.json` to use my fully qualified domain name and HTTPS (as [per the docs](https://taigaio.github.io/taiga-doc/dist/setup-production.html#_servings_https)).

A grep through the front-end showed that `http://localhost:8000` was still in `dist/js/app-loader.js`. Changing that to `https://mydomain.com` fixed my problem.

I'm new to Angular, so I don't know if `app-loader.js` needs to be changed to respect the settings configured in `config.json`, or if the production setup docs just need to be altered to mention that the URL needs to be changed in 2 places when configuring SSL.

**Comment by bameda** [comment]
Hi @pigmonkey, could you please send your question to the mailing list? https://groups.google.com/forum/#!forum/taigaio

We are trying to use github only for bugs and the mailing list for support and questions.

We have a support page with some useful information too at https://taiga.io/support/

Thank you very much.
