### ISSUE TITLE
Default theme is missing

### ISSUE THREAD

**Issue by sattha** [taigaio/taiga-front-dist#21]
Version 4.2.1-stable
It's come with theme "Taiga" only, another 2 themes are missing from select drop down?

any clue?

**Comment by han911976** [comment]
theme could be added by typing in the name to the conf.json
I am using this and it works fine

...
themes": ["taiga","material-design","high-contrast"],
...

**Comment by alexhermida** [comment]
@sattha as @han911976 said you have to add your custom configuration to `conf.json` file.

```
  "defaultLanguage": "en",
  "themes": ["taiga", "material-design", "high-contrast"],
  "defaultTheme": "taiga",
```
