### ISSUE TITLE
Wiki page blank.

### ISSUE THREAD

**Issue by bentinata** [taigaio/taiga-front-dist#6]
I experience blank page on wiki and team page. Any ideas how to resolve it?

![image](https://cloud.githubusercontent.com/assets/3183661/10241195/f46c3a3c-690f-11e5-9813-717ba68f3ed3.png)

EDIT: Maybe it have something with taigaio/taiga-events#4? 'Cause I also experiencing that.

**Comment by superalex** [comment]
Could you please check your javascript console to see if there is any error?

**Comment by bentinata** [comment]
I think it's because I'm using master build. Stable build doesn't have that bug.

Javascript console output is taigaio/taiga-events#4. It's different issue, other than that, no error.
Maybe I should close this issue. Thanks. :)

**Comment by superalex** [comment]
Probably that's the reason, the master branch is actually a bit unstable ;)

Regards!,
