### ISSUE TITLE
Cannot make personal customization

### ISSUE THREAD

**Issue by adebayo-dealdey** [taigaio/taiga-front-dist#8]
Hi Team Taiga.io

I was quite confused about recent update which fully depends on https://github.com/taiga-io/taiga-front . It simply mean that I can make adjustments to my copy of taiga if required. I want to add more custom fields from the source code and zoom, all is lost to your repo. Kindly correct me if I am wrong. Thanks.

**Comment by superalex** [comment]
Hello @adebayo-dealdey,

Sorry but I don't know if I understand what happened exactly. 

- You had a local copy of taiga-front-dist for your instance
- You customized that taiga-front-dist source files (js, html, css...)
- You updated taiga-front-dist and you lost your changes

That's what happened?

**Comment by adebayo-dealdey** [comment]
I noticed that taiga-front/dist.js points back to this repo which means I can't customize the repo like i can with development version installation.

**Comment by superalex** [comment]
Hello @adebayo-dealdey 

If you want to customize the front app you shouldn't just overwrite the files because when you update your repo you will lose the changes. Probably you should base your code on one of the existing taiga-contrib-repos and use the plugins system, for example the slack one -> https://github.com/taigaio/taiga-contrib-slack

Regards,

**Comment by adebayo-dealdey** [comment]
@superalex In that case, what I need is to append some line of codes to the existing base code, how do I change my basecode to my forked version? Thanks for your time.

**Comment by superalex** [comment]
The best option should be you choose one of the Taiga plugins and to see how they do it.

Regards!,

**Comment by adebayo-dealdey** [comment]
@superalex Yes, I will do that but I want to see the possibility of redirecting first as creating a plugin will take me much time. I have the customization on my own forked repo already. It doesn't seems to point even after changing the value on taiga-front-dist/dist.js `var repo = 'https://github.com/taigaio/taiga-front';`

**Comment by superalex** [comment]
Sorry but dist.js file from taiga-front-dist repo is autogenerated from taiga-front repo (https://github.com/taigaio/taiga-front) so just updating that value there wont affect to anything...

Regards!,

**Comment by adebayo-dealdey** [comment]
@superalex Do you mean the dist.js file in my local repo is been updated? Because I think that is what points to taiga-front on own repo as well.

**Comment by superalex** [comment]
Sorry @adebayo-dealdey but I think you are not using taiga repos properly:

 - taiga-front-dist (https://github.com/taigaio/taiga-front-dist) is the compiled version of taiga-front (https://github.com/taigaio/taiga-front)
 - dist.js file from taiga-contrib-dist repo shouldn't be used for anything, is just a command taiga-team uses to build the the taiga-contrib-dist compiled version, it will overwrite your dist folder

If you want to customize the taiga-front code you should use the taiga-front repo (https://github.com/taigaio/taiga-front)

**Comment by adebayo-dealdey** [comment]
I think i understand your point of view, Can I make a suggestion about
migrating a US or Sprint between Projects? Thanks.

**Comment by superalex** [comment]
Sure!, actually the Taiga API supports that feature and we have existing enhancement requests for them :)

**Comment by adebayo-dealdey** [comment]
I want to ask what djmail in the django adminstrator end is meant for.
Thanks.

On Tue, Jan 12, 2016 at 7:44 AM, Alejandro <notifications@github.com> wrote:

> Sure!, actually the Taiga API supports that feature and we have existing
> enhancement requests for them :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front-dist/issues/8#issuecomment-170814990>
> .
>



-- 
Regards,
*Adebayo Akinlaja*
Software Developer

[image: http://www.dealdey.com] <http://www.dealdey.com/> [image:
http://www.lyf.ng] <http://www.promohub.ng/>  <http://www.lyf.ng/>
DealDey Limited
23, Sura Mogaji Street, Off Coker Road, Ilupeju, Lagos

: 0809-355-7981
: internalcommunication@dealdey.com
: /dealdey <https://www.facebook.com/DealDey>
: @dealdey <https://twitter.com/dealdey>

*Over 30,000 businesses have been getting free customer leads from Lyf.ng
<http://lyf.ng/>. What are you waiting for? List your business
<http://www.lyf.ng/home/advertise> for free today​.​*

Disclaimer*
This e-mail (including the attachments) is confidential and may contain
vital information relating to DealDey Limited. If you are not the intended
addressee, you have received this e-mail in error. You may not use,
distribute, disclose or copy any of the information contained within it,
and it may be unlawful to do so. If you are not the intended recipient
please notify the sender by returning this e-mail to *(adebayo@dealdey.com
<adebayo@dealdey.com>) *and destroy all copies.

**Comment by superalex** [comment]
djmail is a django application we use to construct the templates but it has no utility in the admin area.

Please, if the questions differ from the original one it's better you write to the public mail list with a different topic for each question -> taigaio@googlegroups.com, this way we could keep the information better organized and it will be more useful for other users.

Regards!

**Comment by adebayo-dealdey** [comment]
Thanks. I will.

On Thu, Jan 14, 2016 at 8:07 AM, Alejandro <notifications@github.com> wrote:

> djmail is a django application we use to construct the templates but it
> has no utility in the admin area.
>
> Please, if the questions differ from the original one it's better you
> write to the public mail list with a different topic for each question ->
> taigaio@googlegroups.com, this way we could keep the information better
> organized and it will be more useful for other users.
>
> Regards!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front-dist/issues/8#issuecomment-171557965>
> .
>



-- 
Regards,
*Adebayo Akinlaja*
Software Developer

[image: http://www.dealdey.com] <http://www.dealdey.com/> [image:
http://www.lyf.ng] <http://www.promohub.ng/>  <http://www.lyf.ng/>
DealDey Limited
23, Sura Mogaji Street, Off Coker Road, Ilupeju, Lagos

: 0809-355-7981
: internalcommunication@dealdey.com
: /dealdey <https://www.facebook.com/DealDey>
: @dealdey <https://twitter.com/dealdey>

*Over 30,000 businesses have been getting free customer leads from Lyf.ng
<http://lyf.ng/>. What are you waiting for? List your business
<http://www.lyf.ng/home/advertise> for free today​.​*

Disclaimer*
This e-mail (including the attachments) is confidential and may contain
vital information relating to DealDey Limited. If you are not the intended
addressee, you have received this e-mail in error. You may not use,
distribute, disclose or copy any of the information contained within it,
and it may be unlawful to do so. If you are not the intended recipient
please notify the sender by returning this e-mail to *(adebayo@dealdey.com
<adebayo@dealdey.com>) *and destroy all copies.
